# -*- coding: utf-8 -*-
"""Untitled112.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145XxbIRuuPc1sbTMEwQ6-IEZGcWltRDR
"""

pip install smolagents

!pip install litellm -q

import os
from google.colab import userdata
os.environ['HF_TOKEN'] = userdata.get('HF_TOKEN')
os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

from smolagents import CodeAgent, HfApiModel

model=HfApiModel()

agent = CodeAgent(tools=[], model=model)

agent.run("what is 24*7")

from smolagents import  DuckDuckGoSearchTool

CodeAgent(tools=[DuckDuckGoSearchTool()], model=model)

agent.run('tell me  about the generative ai 2025 ')

agent.run("fetch the share price of google from 2020 to 2025")



agent.run("fetch the share price of google from 2020 to 2025")

agent=CodeAgent(tools=[DuckDuckGoSearchTool()], model=HfApiModel(), additional_authorized_imports=['math', 'pandas','requests','bs4','matplotlib','yfinance'])

!pip install matplotlib
!pip install yfinance matplotlib

agent.run("fetch the share price of google from 2020 to 2025, and create a scatter graph from it")

agent.run("fetch the share price of google from 2020 to 2025, and create a line graph from it")

from smolagents import Tool

class HFModelDownloadsTool(Tool):
    name = "model_download_counter"
    description = """
    This is a tool that returns the most downloaded model of a given task on the Hugging Face Hub.
    It returns the name of the checkpoint.
    """
    inputs = {
        "task": {
            "type": "string",
            "description": "the task category (such as text-classification, depth-estimation, etc)",
        }
    }
    output_type = "string"

    def forward(self, task: str):
        from huggingface_hub import list_models
        model = next(iter(list_models(filter=task, sort="downloads", direction=-1)))
        return model.id

model_downloads_tool = HFModelDownloadsTool()



agent=CodeAgent(tools=[model_downloads_tool], model=HfApiModel(), additional_authorized_imports=['math', 'pandas','requests','bs4','matplotlib','yfinance'])

agent.run("what is the most downloaded model text to image generation")

from smolagents import ToolCallingAgent

agent= ToolCallingAgent(tools=[DuckDuckGoSearchTool()], model=HfApiModel())

agent.run("could you getthe few topic of the blog at 'https://www.reddit.com/r/TechSEO/comments/14rh5fs/best_url_structure_for_blog_posts_in_2023/?rdt=39938' !")

